/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import context.AppContext;
import domain.Conference;

import static domain.ConferenceParticipation.Role.*;
import domain.User;
import drivers.ConferenceParticipationStoreService;
import drivers.ConferenceStoreService;
import drivers.UserStoreService;

import java.util.Vector;
import static utilities.Utilities.setAlert;

/**
 *
 * @author julia
 */
public class ViewAddUserToMyConf extends javax.swing.JFrame {

    //Usuario logeado
    private User objUser;
    //Servicio de conferencias
    private ConferenceStoreService objConferenceStoreService;
    //Servicio de papers
    private UserStoreService objUserStoreService;
    
    private ConferenceParticipationStoreService objParticipationService;

    private Vector<Conference> vecMyConferences;

    /**
     * Creates new form ViewAddUserToMyConf
     */
    public ViewAddUserToMyConf() {
        AppContext appContext = AppContext.getInstance();
        this.objUser = appContext.getLoggedUser();
        this.objConferenceStoreService = appContext.getConferenceStoreService();
        this.objUserStoreService = appContext.getUserStoreService();
        objParticipationService = new ConferenceParticipationStoreService(appContext.getRepositoryConferenceParticipation());
        vecMyConferences = new Vector(this.objConferenceStoreService.listConferenceByOwner(objUser));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitleAddUserToMyConf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitleEmail = new javax.swing.JLabel();
        jLabelTitleTitleConference = new javax.swing.JLabel();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jButtonAddUser = new javax.swing.JButton();
        jComboBoxConference = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 213, 224));

        jLabelTitleAddUserToMyConf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleAddUserToMyConf.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleAddUserToMyConf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleAddUserToMyConf.setText("AÑADIR USUARIO A MI CONFERENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleAddUserToMyConf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitleAddUserToMyConf)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(244, 240, 216));

        jLabelTitleEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleEmail.setText("Email");

        jLabelTitleTitleConference.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleTitleConference.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleTitleConference.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleTitleConference.setText("Titulo de conferencia");

        jButtonAddUser.setText("Añadir");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jComboBoxConference.setModel(new javax.swing.DefaultComboBoxModel<>(this.vecMyConferences));
        jComboBoxConference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConferenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jComboBoxConference, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButtonAddUser)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTitleTitleConference, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleEmail)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jComboBoxConference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddUser)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(101, Short.MAX_VALUE)
                    .addComponent(jLabelTitleTitleConference)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        //Usuario asistente
        User objUserAsist = null;
        //Conferencia a asigna
        Conference conference = (Conference) this.jComboBoxConference.getSelectedItem();        
        
        String inputEmail = this.jTextFieldEmail1.getText();        
        
        //Buscamos el usuario como asistente a la conferencia
        objUserAsist = this.objUserStoreService.getUserByEmail(inputEmail);
        
        if (objUserAsist == null) {
            setAlert("Usuario no encontrado", "");
            return;
        }
        if (conference == null) {
            setAlert("Conferencia no encontrada", "");
            return;
        }
        
        //Finalmente añadimos el obj ConferenceParticipation de esta forma añadiendo al usuario
        boolean varFlag = this.objParticipationService.createConferenceParticipation(objUserAsist, conference, AUTHOR);
        if (varFlag) {
            setAlert("Guardado exitoso", "");
        } else {
            setAlert("Error", "Error al guardar usuario");
            return;
        }
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jComboBoxConferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConferenceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JComboBox<Conference> jComboBoxConference;
    private javax.swing.JLabel jLabelTitleAddUserToMyConf;
    private javax.swing.JLabel jLabelTitleEmail;
    private javax.swing.JLabel jLabelTitleTitleConference;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEmail1;
    // End of variables declaration//GEN-END:variables
}
