/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
<<<<<<< HEAD
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domain.User;
import drivers.UserStoreService;
import javax.swing.JFrame;

/**
 *
 * @author julia
 */
public class ViewMainMenu extends javax.swing.JFrame {
//Usuario logeado
    User fldUser;
    private UserStoreService fldUserStoreService; 

    public ViewMainMenu(UserStoreService fldUserStoreService,User fldUser) {
        this.fldUser = fldUser;
    }

    public User getFldUser() {
        return fldUser;
    }

    public void setFldUser(User fldUser) {
        this.fldUser = fldUser;
    }
    
    /**
     * Creates new form ViewMainMenu
     */
    public ViewMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainMenu = new javax.swing.JPanel();
        jLabelImgLogo = new javax.swing.JLabel();
        jMenuBarOptions = new javax.swing.JMenuBar();
        jMenuConferences = new javax.swing.JMenu();
        jMenuMyConferences = new javax.swing.JMenu();
        jMenuAssistantConference = new javax.swing.JMenu();
        jMenuMyPapers = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMainMenu.setBackground(new java.awt.Color(244, 240, 216));
        jPanelMainMenu.setLayout(new java.awt.BorderLayout());

        jLabelImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PosibleLogo.jpg"))); // NOI18N
        jLabelImgLogo.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabelImgLogo.setMinimumSize(new java.awt.Dimension(10, 10));
        jPanelMainMenu.add(jLabelImgLogo, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelMainMenu, java.awt.BorderLayout.CENTER);

        jMenuBarOptions.setBackground(new java.awt.Color(199, 213, 224));
        jMenuBarOptions.setForeground(new java.awt.Color(27, 40, 56));

        jMenuConferences.setBackground(new java.awt.Color(102, 192, 244));
        jMenuConferences.setForeground(new java.awt.Color(27, 40, 56));
        jMenuConferences.setText("Conferencias");
        jMenuConferences.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuMyConferences.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/presentation_426378.jpg"))); // NOI18N
        jMenuMyConferences.setText("Mis conferencias");
        jMenuMyConferences.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuMyConferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMyConferencesMouseClicked(evt);
            }
        });
        jMenuConferences.add(jMenuMyConferences);

        jMenuAssistantConference.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/public-speaking_5455385.jpg"))); // NOI18N
        jMenuAssistantConference.setText("Conferencias a las que asisto");
        jMenuAssistantConference.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuAssistantConference.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAssistantConferenceMouseClicked(evt);
            }
        });
        jMenuConferences.add(jMenuAssistantConference);

        jMenuBarOptions.add(jMenuConferences);

        jMenuMyPapers.setBackground(new java.awt.Color(102, 192, 244));
        jMenuMyPapers.setForeground(new java.awt.Color(27, 40, 56));
        jMenuMyPapers.setText("Mis trabajos");
        jMenuMyPapers.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuMyPapers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMyPapersMouseClicked(evt);
            }
        });
        jMenuBarOptions.add(jMenuMyPapers);

        setJMenuBar(jMenuBarOptions);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMyConferencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMyConferencesMouseClicked
        // TODO add your handling code here:
        ViewMyConferences objViewMyConferences = new ViewMyConferences();
        objViewMyConferences.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objViewMyConferences.setVisible(true);
    }//GEN-LAST:event_jMenuMyConferencesMouseClicked

    private void jMenuAssistantConferenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAssistantConferenceMouseClicked
        // TODO add your handling code here:
        ViewAssistantConference objViewAssistantConference = new ViewAssistantConference();
        objViewAssistantConference.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objViewAssistantConference.setVisible(true);
    }//GEN-LAST:event_jMenuAssistantConferenceMouseClicked

    private void jMenuMyPapersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMyPapersMouseClicked
        // TODO add your handling code here:
        ViewMyPapers objViewMyPapers = new ViewMyPapers();
        objViewMyPapers.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objViewMyPapers.setVisible(true);
    }//GEN-LAST:event_jMenuMyPapersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImgLogo;
    private javax.swing.JMenu jMenuAssistantConference;
    private javax.swing.JMenuBar jMenuBarOptions;
    private javax.swing.JMenu jMenuConferences;
    private javax.swing.JMenu jMenuMyConferences;
    private javax.swing.JMenu jMenuMyPapers;
    private javax.swing.JPanel jPanelMainMenu;
    // End of variables declaration//GEN-END:variables
}