/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import co.edu.unicauca.cuychair.common.notificationPlugin.IEmailPlugin;
import context.AppContext;
import domain.Conference;
import domain.ConferenceParticipation;
import domain.Paper;
import domain.User;
import drivers.ConferenceStoreService;
import drivers.PaperStoreService;
import plugin.manager.EmailPluginManager;

import java.util.Vector;
import static utilities.Utilities.setAlert;

/**
 *
 * @author julia
 */
public class ViewUploadPaper extends javax.swing.JFrame {
    User objUser;//User logeado
    PaperStoreService objPaperStoreService;//Servicio de almacenamiento de paper
    ConferenceStoreService objConferenceStoreService;
    Vector<Conference> conferenceList;
    /**
     * Creates new form ViewUploadPaper
     */
    public ViewUploadPaper() {
        ObserverJobs obj=new ObserverJobs();
        obj.setVisible(true);
        AppContext appContext = AppContext.getInstance();
        this.objUser=appContext.getLoggedUser();
        this.objPaperStoreService = new PaperStoreService(appContext.getRepositoryPaper());
        objPaperStoreService.addObserver(obj);
        this.objConferenceStoreService = new ConferenceStoreService(appContext.getRepositoryConference());
        this.conferenceList = new Vector<>( objConferenceStoreService.listConferencesRelatedTo(objUser, ConferenceParticipation.Role.AUTHOR));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitleUploadPaper = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelConferencia = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonUploadPaper = new javax.swing.JButton();
        jTextConference = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 213, 224));

        jLabelTitleUploadPaper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleUploadPaper.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleUploadPaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleUploadPaper.setText("SUBIR TRABAJO A CONFERENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleUploadPaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTitleUploadPaper)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(244, 240, 216));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Titulo:");

        jLabelDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescripcion.setText("Descripción:");

        jLabelConferencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelConferencia.setForeground(new java.awt.Color(0, 0, 0));
        jLabelConferencia.setText("Conferencia:");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jButtonUploadPaper.setText("Subir");
        jButtonUploadPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadPaperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelConferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextConference, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jButtonUploadPaper)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConferencia)
                    .addComponent(jTextConference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescripcion))
                .addGap(18, 18, 18)
                .addComponent(jButtonUploadPaper)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadPaperActionPerformed
        String title = this.jTextFieldTitulo.getText();
        String description = this.jTextFieldDescription.getText();
        String conference = this.jTextConference.getText();
        int id=Integer.parseInt(conference);
        Conference conference1=objConferenceStoreService.getConferenceById(id);
        Paper objPaper = new Paper(title,description,this.objUser, conference1);
        boolean varFlag = this.objPaperStoreService.storePaper(objPaper);
        if(varFlag){
            setAlert("Subida de trabajo", "exitosa");
        }else{
            setAlert("Subida de trabajo", "fallida");
        }

        EmailPluginManager manager=EmailPluginManager.getInstance();
        IEmailPlugin plugin= manager.getDeliveryPlugin();
        plugin.notifySendJobs(objPaper,conference1,objUser);
    }//GEN-LAST:event_jButtonUploadPaperActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUploadPaper;
    private javax.swing.JLabel jLabelConferencia;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTitleUploadPaper;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextConference;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
