/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import context.AppContext;
import domain.Conference;
import domain.ConferenceParticipation;
import domain.User;
import drivers.ConferenceStoreService;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julia
 */
public class ViewMyConferences extends javax.swing.JFrame {
    //Usuario logeado
    private User objUser;
    //Servicio de conferencias
    private ConferenceStoreService objConferenceStoreService;
    /**
     * Creates new form ViewMyConferences
     */
    
    public ViewMyConferences() {
        initComponents();
        AppContext appContext = AppContext.getInstance();
        this.objUser=appContext.getLoggedUser();
        this.objConferenceStoreService=new ConferenceStoreService(appContext.getRepositoryConference());
        InitTable();
    }
    private void InitTable()
    {
       DefaultTableModel model= new DefaultTableModel();       
       model.addColumn("Titulo");       
       model.addColumn("Ciudad");
       model.addColumn("Descripción");
       model.addColumn("Fecha");
       this.jTableMyConferences.setModel(model);
    }
    //Limpia una tabla
    public void cleanTable(){
        DefaultTableModel modelo=(DefaultTableModel) this.jTableMyConferences.getModel();
        int filas=this.jTableMyConferences.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }        
    }
     
    //Llenar tabla
     private void fillTable()
    {
        DefaultTableModel model=(DefaultTableModel) this.jTableMyConferences.getModel();
        cleanTable();
        ArrayList<Conference> conferenceList
                = (ArrayList<Conference>) this.objConferenceStoreService.listAssistantConferences(objUser);
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        
        for (int i = 0; i < conferenceList.size(); i++) {
            //Solo añade la fila si el usuario Id coincide con el del usuario logeado
            if(conferenceList.get(i).getConferenceOrganizer().getUserId()==this.objUser.getUserId()){
                Object [] row= { 
                conferenceList.get(i).getTitle(),
                conferenceList.get(i).getCity(),
                conferenceList.get(i).getDescription(),
                formatter.format(conferenceList.get(i).getDate())
                };
                model.addRow(row);
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUp = new javax.swing.JPanel();
        jLabelTituloMisConferencias = new javax.swing.JLabel();
        jPanelDown = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMyConferences = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanelUp.setBackground(new java.awt.Color(199, 213, 224));

        jLabelTituloMisConferencias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloMisConferencias.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloMisConferencias.setText("MIS CONFERENCIAS");

        javax.swing.GroupLayout jPanelUpLayout = new javax.swing.GroupLayout(jPanelUp);
        jPanelUp.setLayout(jPanelUpLayout);
        jPanelUpLayout.setHorizontalGroup(
            jPanelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabelTituloMisConferencias)
                .addGap(139, 139, 139))
        );
        jPanelUpLayout.setVerticalGroup(
            jPanelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelTituloMisConferencias)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanelUp, java.awt.BorderLayout.PAGE_START);

        jPanelDown.setBackground(new java.awt.Color(244, 240, 216));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTableMyConferences.setBackground(new java.awt.Color(172, 156, 124));
        jTableMyConferences.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableMyConferences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Ciudad", "Descripción", "Fecha"
            }
        ));
        jTableMyConferences.setGridColor(new java.awt.Color(172, 156, 124));
        jScrollPane1.setViewportView(jTableMyConferences);
        if (jTableMyConferences.getColumnModel().getColumnCount() > 0) {
            jTableMyConferences.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableMyConferences.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTableMyConferences.getColumnModel().getColumn(3).setPreferredWidth(7);
        }

        jButtonRefresh.setText("Actualizar");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDownLayout = new javax.swing.GroupLayout(jPanelDown);
        jPanelDown.setLayout(jPanelDownLayout);
        jPanelDownLayout.setHorizontalGroup(
            jPanelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDownLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelDownLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButtonRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDownLayout.setVerticalGroup(
            jPanelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRefresh)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDown, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelTituloMisConferencias;
    private javax.swing.JPanel jPanelDown;
    private javax.swing.JPanel jPanelUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMyConferences;
    // End of variables declaration//GEN-END:variables
}
