/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import context.AppContext;
import domain.Conference;
import domain.ConferenceParticipation;
import static domain.ConferenceParticipation.Role.AUTHOR;
import domain.User;
import drivers.ConferenceStoreService;
import drivers.UserStoreService;
import java.util.ArrayList;
import static utilities.Utilities.setAlert;

/**
 *
 * @author julia
 */
public class ViewAddUserToMyConf extends javax.swing.JFrame {
    //Usuario logeado
    private User objUser;
    //Servicio de conferencias
    private ConferenceStoreService objConferenceStoreService;
    //Servicio de papers
    private UserStoreService objUserStoreService;
    /**
     * Creates new form ViewAddUserToMyConf
     */
    public ViewAddUserToMyConf() {
        AppContext appContext = AppContext.getInstance();
        this.objUser=appContext.getLoggedUser();
        this.objConferenceStoreService= new ConferenceStoreService(appContext.getRepositoryConference());
        this.objUserStoreService= new UserStoreService(appContext.getRepositoryUser());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitleAddUserToMyConf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitleEmail = new javax.swing.JLabel();
        jLabelTitleTitleConference = new javax.swing.JLabel();
        jTextFieldConfTitle = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jButtonAddUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 213, 224));

        jLabelTitleAddUserToMyConf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleAddUserToMyConf.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleAddUserToMyConf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleAddUserToMyConf.setText("AÑADIR USUARIO A MI CONFERENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleAddUserToMyConf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitleAddUserToMyConf)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(244, 240, 216));

        jLabelTitleEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleEmail.setText("Email");

        jLabelTitleTitleConference.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitleTitleConference.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleTitleConference.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleTitleConference.setText("Titulo de conferencia");

        jButtonAddUser.setText("Añadir");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jTextFieldConfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonAddUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTitleTitleConference, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(115, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(97, 97, 97)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jTextFieldConfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddUser)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(101, Short.MAX_VALUE)
                    .addComponent(jLabelTitleTitleConference)
                    .addContainerGap(101, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        int varAux=-1;
        //Usuario asistente
        User objUserAsist = null; 
        //Conferencia a asigna
        Conference conference = null;
        //Conferencias del usuario logeado
        ArrayList<Conference> conferenceList
                = (ArrayList<Conference>)this.objConferenceStoreService.listConferencesRelatedTo(this.objUser, ConferenceParticipation.Role.AUTHOR);
        //Buscamos el usuario como asistente a la conferencia
        for(int j=0;j<conferenceList.size();j++){
            //Si coincide lo guardamos
            if(this.objUserStoreService.listUsers().get(j).getUserEmail().equals(this.jTextFieldEmail1)){
                objUserAsist=this.objUserStoreService.listUsers().get(j);
                
            }
        }
        if(objUserAsist==null){
            setAlert("Usuario no encontrado","");
            return;
        }
        for(int i=0;i<conferenceList.size();i++){
            //Comparamos si la conferencia digitada coincide con alguna
            if(conferenceList.get(i).getTitle().equals(this.jTextFieldConfTitle)){
                //Guardamos la conferencia en un obj temporal
                conference = conferenceList.get(i);
            } 
        }
        if(conference==null){
            setAlert("Conferencia no encontrada","");
            return;
        }
        //Creamos un obj de tipo ConferenceParticipations para añadirlo a la lista
        ConferenceParticipation objConferenceParticipation = new ConferenceParticipation(0,objUserAsist,conference,AUTHOR);
        //Finalmente añadimos el obj ConferenceParticipation de esta forma añadiendo al usuario
        boolean varFlag=conferenceList.get(varAux).getParticipations().add(objConferenceParticipation);
        if(varFlag){
            setAlert("Guardado exitoso","");
        }else{
            setAlert("Error","Error al guardar usuario");
            return;
        }
    }//GEN-LAST:event_jButtonAddUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JLabel jLabelTitleAddUserToMyConf;
    private javax.swing.JLabel jLabelTitleEmail;
    private javax.swing.JLabel jLabelTitleTitleConference;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldConfTitle;
    private javax.swing.JTextField jTextFieldEmail1;
    // End of variables declaration//GEN-END:variables
}
